### ISSUE TITLE
How to use this repository to simulate LiDARs in Carla

### ISSUE THREAD

**Issue by amansrf** [SigmaEmbeddedEngineering-eg/Real2Sim_gazebo#1]
Are there any specific instructions on how this repo could be used with Carla?
I am trying to simulate Luminar's Hydra LiDAR in Carla.

**Comment by khaledelmadawi** [comment]
1st you need to train the network on real luminar traces and replace the path of the DNN to the new path:
https://github.com/SigmaEmbeddedEngineering-eg/Real2Sim_gazebo/blob/master/real2sim_lidar_sensor/models/hatchback_ego/model.sdf#L124

2nd you need to reconfigure the horizontal and vertical configurations to the resolution of ur lidar sensor:
https://github.com/SigmaEmbeddedEngineering-eg/Real2Sim_gazebo/blob/master/real2sim_lidar_sensor/models/hatchback_ego/model.sdf#L92
https://github.com/SigmaEmbeddedEngineering-eg/Real2Sim_gazebo/blob/master/real2sim_lidar_sensor/models/hatchback_ego/model.sdf#L98
3rd as per my knowledge Luminar has different artifacts which require some preprocessing, you will need to add them.
 we can have a short call to share ideas, you can contact me @ khalid.elmadawi@sigma.se
